### ISSUE TITLE
/usr/local/etc/crashplan: no such file or directory on START

### ISSUE THREAD

**Issue by brettveenstra** [ajkerrigan/crashplan-docker-synology#11]
First off: thanks for a great package!

I'm trying to install per Wiki instructions after a fresh install of DSM and Docker.

When starting the container via terminal, I'm getting seeing this:

	/usr/local/etc/rc.d/S99crashplandocker.sh start
	Found the user variables file. Updating...
	CRASHPLAN_DIR=/usr/local/etc/crashplan
	DATA_DIR=/volume1/CrashPlanBackups
	USER_VOLUMES=-v /volume1:/volume1:ro
	No existing CrashPlan container found. Running image "ajkerrigan/crashplan".
	Unable to find image 'ajkerrigan/crashplan:latest' locally
	latest: Pulling from ajkerrigan/crashplan
	f069f1d21059: Pull complete
	ecbeec5633cf: Pull complete
	ea6f18256d63: Pull complete
	54bde7b02897: Pull complete
	a3ed95caeb02: Pull complete
	ce9e695a6234: Pull complete
	346026b9659b: Pull complete
	d900dbe16dec: Pull complete
	c599eff79b5a: Pull complete
	Digest: sha256:cc665edccff63933b6bbdf765a6ea14236908ef28c941c9ff45d31e83e40935e
	Status: Downloaded newer image for ajkerrigan/crashplan:latest
	73f3ca6ad9972962036bfd21094e9a21490602c0e73be431fa4b9abc00a61656
	/var/packages/Docker/target/usr/bin/docker: Error response from daemon: stat /usr/local/etc/crashplan: no such file or directory.

My version info:

- DSM: 6.1-15047
- Docker: 1.11.2, build bf60a63-synology

Looking through issue #9, it gives me hope there is a solution for this but not sure this is the same issue in play.  Any suggestions?

**Comment by ajkerrigan-mdsol** [comment]
Hi there @brettveenstra! With the default configuration, this container attempts to map your host path `/usr/local/etc/crashplan` to `/config` inside the container. It looks like you don't have a `/usr/local/etc/crashplan` on your NAS, so it can't set up that volume mapping. I have two different suggestions that may help, depending on your situation:

**Option 1: Create the Directory**

If this is your first time trying to run CrashPlan on your Synology device, you can try creating that path (`mkdir -p /usr/local/etc/crashplan`) and running the container again.

**Option 2: Point this Script to an Alternate Existing Directory**

If you've been running CrashPlan natively using a different installation method, you'll probably want to find out where your existing installation lives (or lived). It should be a directory named `crashplan` or `CrashPlan`, with subdirectories including `conf` and `id`. (As an example, my pre-Docker installation lived at `/volume/CrashPlan`). Then you can copy `cp-user-vars.sh` from this repository to `/root`, and modify the `CRASHPLAN_DIR` to point to your previous installation path.

I hope one of those options gets you somewhere, let me know how it goes and hopefully we'll get it sorted out :).

**Comment by ghost** [comment]
Hi there @brettveenstra! With the default configuration, this container attempts to map your host path `/usr/local/etc/crashplan` to `/config` inside the container. It looks like you don't have a `/usr/local/etc/crashplan` on your NAS, so it can't set up that volume mapping. I have two different suggestions that may help, depending on your situation:

**Option 1: Create the Directory**

If this is your first time trying to run CrashPlan on your Synology device, you can try creating that path (`mkdir -p /usr/local/etc/crashplan`) and running the container again.

**Option 2: Point this Script to an Alternate Existing Directory**

If you've been running CrashPlan natively using a different installation method, you'll probably want to find out where your existing installation lives (or lived). It should be a directory named `crashplan` or `CrashPlan`, with subdirectories including `conf` and `id`. (As an example, my pre-Docker installation lived at `/volume/CrashPlan`). Then you can copy `cp-user-vars.sh` from this repository to `/root`, and modify the `CRASHPLAN_DIR` to point to your previous installation path.

I hope one of those options gets you somewhere, let me know how it goes and hopefully we'll get it sorted out :).
