### ISSUE TITLE
Don't recommend storing files in /root

### ISSUE THREAD

**Issue by apaloma** [ajkerrigan/crashplan-docker-synology#12]
I had my git repo and cp-user-vars.sh in /root as recommended by the readme and just lost them after a DSM upgrade. Apparently DSM upgrades wipe /root.

**Comment by ghost** [comment]
Thank you for the heads up about this @apaloma, apologies for not responding sooner. I need to take some time to get this fixed. You're right, `/root` is not a good place for those settings to live.
