### ISSUE TITLE
No auth token in /config/id/.ui_info

### ISSUE THREAD

**Issue by j-ittner** [ajkerrigan/crashplan-docker-synology#13]
Hi, thanks to your great documentation I managed to install, configure, and start the crashplan container. Unfortunately I do not manage to connect from my CrashPlan UI. Appears there is no authentication token in `/config/id/.ui_info`:

`# cat /config/id/.ui_info`
gets me
`4243,unRAID`

I expected the format to be:
`4243,<token>,<localhost>`

Any ideas how to fix this / how to connect from the UI?

BTW, I also noticed that the log files in /config/log are not being updated, despite the JAVA process being active. Should I look for logs at another location?

Many thanks!

**Comment by ghost** [comment]
Hmm I haven't touched my setup in a while, but I remember that unRAID usually shows up when the container is starting and CrashPlan isn't fully up and running yet. Here are a couple things to check, and hopefully we'll turn up something helpful:

1. Is this a new setup or did you have something working that broke? @apaloma raised a good point in #12, where custom settings can be lost. I need to take some time and get that settings file moved, likely to `/usr/local/etc/crashplan`. And bump the docker image up to the most recent CrashPlan install while I'm at it, make sure it doesn't break stuff... :)

2. Do you see any helpful error messages in the most recently updated log file? `ls -rtl /config/log` from within the container. `service.log.0` is a good place to check, along with the most recent `upgrade*.log` file. That may help identify a problem that popped up during a version upgrade or service startup.

Let me know how it goes!

**Comment by apaloma** [comment]
I noticed in the docker container, at the end of `/etc/my_init.d/config.sh`, there's these lines
```bash
NETIF=`ip route list | grep "^default via" | awk '{ print $NF }'`
IP=`ifconfig ${NETIF} | grep "inet addr:" | cut -d: -f2 | awk '{ print $1 }'`
echo "4243,unRAID" > /config/id/.ui_info
sed -i -e "s|0.0.0.0|${IP}|" /config/id/.ui_info
```

I commented these out because it would stomp the identity each time the container restarted, and the IP part didn't work anyways. Not sure what the intent was with this.
