### ISSUE TITLE
.ui_info missing

### ISSUE THREAD

**Issue by gridwriter** [ajkerrigan/crashplan-docker-synology#2]
If I set this up on a new Synology, without any pre-existing Crashplan directories, where does the `.ui_info` file end up?

Starting the package works fine, however I cannot find the `.ui_info` file anywhere.

**Comment by ghost** [comment]
Hi there! The _container_ path for `.ui_info` is `/config/id/.ui_info`. The startup script mounts the host path `$CRASHPLAN_DIR` (by default `/usr/local/etc/crashplan`) as the container's `/config` volume, so by default the _host_ path for `.ui_info` is `/usr/local/etc/crashplan/id/.ui_info`. In case it helps, you can confirm the host path of a running container's `/config` volume with this command:

``` bash
docker inspect --format '{{ (index .Volumes "/config") }}' \
`docker ps -qf ancestor=ajkerrigan/crashplan`
```

And relative to that path, you should have `id/.ui_info`. I hope that helps, but please let me know if it doesn't.

**Comment by ghost** [comment]
I've added this information to a [wiki page](https://github.com/ajkerrigan/crashplan-docker-synology/wiki/Common-Questions), so I'm closing the issue. Feel free to reach out if this is still not clear and I'll update the documentation. Thank you!
