### ISSUE TITLE
Make deployment smoother

### ISSUE THREAD

**Issue by ghost** [ajkerrigan/crashplan-docker-synology#8]
The "install" process at this point is some combination of cloning the git repo and then copying and/or symlinking files. That is probably not intimidating to anyone who is in the position to need a script like this in the first place, but it does feel a bit clunky. Since we have the luxury of a somewhat predictable environment, it may be worth having a light install script that does the initial symlinking in one shot.

In that case, it may make sense to "install" `cp-user-vars.sh` by default, with commented out path variables set to the same values as the script defaults. Customization would then be a matter of uncommenting and tweaking lines in that file.

**Comment by ebiancarelli** [comment]
sounds good to me
